version: '3.4'

services:
  instagramclone.api:
    image: ${DOCKER_REGISTRY-}instagramcloneapi
    build:
      context: .
      dockerfile: InstagramClone.Api/Dockerfile
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "Test_Password123?!"
        ACCEPT_EULA: "Y"